[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.flash_mode = dio
board_build.flash_size = 4MB
board_build.partitions = partitions.csv
board_build.f_cpu = 80000000L
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  olikraus/U8g2@^2.35.30
  bblanchon/ArduinoJson@^7.2.1
  adafruit/Adafruit BME280 Library@^2.2.4
  adafruit/Adafruit Unified Sensor@^1.1.14
